// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWb25g2YyCr1_JmXhsFcDFUrWCIl27gyM',
    appId: '1:885717192676:web:af42530617ee56b3e001f1',
    messagingSenderId: '885717192676',
    projectId: 'ecomerceapp-cb93e',
    authDomain: 'ecomerceapp-cb93e.firebaseapp.com',
    storageBucket: 'ecomerceapp-cb93e.appspot.com',
    measurementId: 'G-ERQJGTVRNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsK7KNvZIZpryHzgxTMJUWhtPbDSQRcA',
    appId: '1:885717192676:android:49460508c49c0df3e001f1',
    messagingSenderId: '885717192676',
    projectId: 'ecomerceapp-cb93e',
    storageBucket: 'ecomerceapp-cb93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBklbOFVy0S5hBO_tHKTBgcFtCGir_SnX4',
    appId: '1:885717192676:ios:9212746f1e96b9c8e001f1',
    messagingSenderId: '885717192676',
    projectId: 'ecomerceapp-cb93e',
    storageBucket: 'ecomerceapp-cb93e.appspot.com',
    iosBundleId: 'com.example.classAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBklbOFVy0S5hBO_tHKTBgcFtCGir_SnX4',
    appId: '1:885717192676:ios:9212746f1e96b9c8e001f1',
    messagingSenderId: '885717192676',
    projectId: 'ecomerceapp-cb93e',
    storageBucket: 'ecomerceapp-cb93e.appspot.com',
    iosBundleId: 'com.example.classAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWb25g2YyCr1_JmXhsFcDFUrWCIl27gyM',
    appId: '1:885717192676:web:7cc25e3e3afeb960e001f1',
    messagingSenderId: '885717192676',
    projectId: 'ecomerceapp-cb93e',
    authDomain: 'ecomerceapp-cb93e.firebaseapp.com',
    storageBucket: 'ecomerceapp-cb93e.appspot.com',
    measurementId: 'G-ETKLJ2GE22',
  );

}